modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Towdium/JustEnoughCharacters/issues"

[[mods]]
modId="jecharacters"
version="${file.jarVersion}"
displayName="Just Enough Characters"
displayURL="https://github.com/Towdium/JustEnoughCaracters"
credits="Thanks to the MCP, Forge and FML guys"
authors="Towdium"
description="Pinyin search for JEI and more."
