modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Towdium/JustEnoughCharacters/issues"

[[mods]]
modId="jecharacters"
version="${file.jarVersion}"
displayName="Just Enough Characters"
displayURL="https://github.com/Towdium/JustEnoughCaracters"
credits="Thanks to TartaricAcid, 3TUSK, Seraph_JACK, Snownee and many people for their efforts for development of the Chinese modding community."
authors="Towdium"
description="Pinyin search for JEI and more."
